#!/usr/bin/env node
// The engine lives in exactly one place: src/ at the repository root.
//
// The VS Code extension ships a working CLI inside its .vsix, and a packaged
// extension cannot reference files outside its own folder, so it needs a
// physical copy. That copy is generated by this script and must never be
// edited by hand.
//
//   node scripts/sync-engine.mjs           copy src/ -> vscode-extension/src/
//   node scripts/sync-engine.mjs --check   exit 1 if the copy is out of date
//
// `--check` runs in the test suite so the two trees cannot silently diverge
// again, which is how they forked in the first place.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'src');
const target = path.join(root, 'vscode-extension', 'src');

const BANNER = '// GENERATED FILE - do not edit. Source: src/%NAME% (npm run sync:engine)\n';

export function engineFiles() {
  return fs.readdirSync(source).filter((file) => file.endsWith('.js')).sort();
}

export function expectedContent(file) {
  return BANNER.replace('%NAME%', file) + fs.readFileSync(path.join(source, file), 'utf8');
}

function currentContent(file) {
  const dest = path.join(target, file);
  return fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : null;
}

export function drift() {
  return engineFiles().filter((file) => currentContent(file) !== expectedContent(file));
}

function main() {
  const check = process.argv.includes('--check');
  const stale = drift();

  if (check) {
    if (!stale.length) {
      console.log(`engine in sync (${engineFiles().length} files)`);
      return 0;
    }
    console.error(`vscode-extension/src is out of date: ${stale.join(', ')}`);
    console.error('Run: npm run sync:engine');
    return 1;
  }

  fs.mkdirSync(target, { recursive: true });
  for (const file of engineFiles()) {
    fs.writeFileSync(path.join(target, file), expectedContent(file));
  }
  console.log(`synced ${engineFiles().length} engine files to vscode-extension/src`);
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main());
}
